### ISSUE TITLE
Create Documentation

### ISSUE THREAD

**Issue by marimariavi** [MeeFoundation/docs#6]
Check JS SDK readme
Website, blog, docs portal - work on the dev documentation

**Comment by lemind** [comment]
0. Beginning
* It would be great to see overall scheme how the Mee universe works and an introduction about it. Like from the beginning "You do not want to share your information so you can keep it in an wallet. This is a provider with mee button, so you get the app and so on". 
* "If you’re a service provider" Am I a service provider? Would be great to have a clear answer about it.
* I guess some of Paul's presentation slides can be useful in this section

1. Terminology
* "The person that has installed and uses the smartwallet on one or more of their devices (e.g. phone, tablet, laptop, home server, etc.)." A person? "their" - his/her?
* "Subject - A thing about which claims are made." Sounds vague. I do not think we can use "a thing" in terminology
* Need to bring some clarity about terms

**Comment by lemind** [comment]
2. Connect with Mee
* How the button will look like? Can I change or pick the button's view?
* I've added a link to SDK rep
3. Use Cases
* If we have potential use cases it seems reasonable to have ones we already have
* Huge page; let's split it
4. User stories
* Is that potential user stories or we have already had that
